<?php

use Illuminate\Database\Seeder;

class OnomatopoeiasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
         DB::table("onomatopoeias")->truncate();
         
         DB::table("onomatopoeias")->insert(
      [
        [
          'id'=>'1',
          'technique_id'=>'1',
          'name'=>'チュイーン',
        ],
        [
          'id'=>'2',
          'technique_id'=>'1',
          'name'=>'ウイーン',
        ],
        [
          'id'=>'3',
          'technique_id'=>'1',
          'name'=>'ウィーン',
        ],
        [
          'id'=>'4',
          'technique_id'=>'2',
          'name'=>'チューンウンウン',
        ],
         [
          'id'=>'5',
          'technique_id'=>'2',
          'name'=>'ウンウン',
        ],
        [
          'id'=>'6',
          'technique_id'=>'2',
          'name'=>'ワンワン',
        ],
        [
          'id'=>'7',
          'technique_id'=>'2',
          'name'=>'チュワワーン',
        ],
        [
          'id'=>'8',
          'technique_id'=>'3',
          'name'=>'キンコーン',
        ],
         [
         'id'=>'9',
         'technique_id'=>'3',
         'name'=>'キンコンカーンコーン',
        ],
         [
         'id'=>'10',
         'technique_id'=>'3',
         'name'=>'キンコン',
        ],
        [
         'id'=>'11',
         'technique_id'=>'4',
         'name'=>'キュイーン',
        ],
         [
         'id'=>'12',
         'technique_id'=>'4',
         'name'=>'ピッキーン',
        ],
         [
         'id'=>'13',
         'technique_id'=>'4',
         'name'=>'キューン',
        ],
         [
          'id'=>'14',
          'technique_id'=>'5',
          'name'=>'ギュイーン',
        ],
          [
         'id'=>'15',
         'technique_id'=>'5',
         'name'=>'キューウィーン',
        ],
         [
         'id'=>'16',
         'technique_id'=>'5',
         'name'=>'ギューウィーン',
        ],
        [
          'id'=>'17',
          'technique_id'=>'6',
          'name'=>'ギー',
        ],
         [
          'id'=>'18',
          'technique_id'=>'6',
          'name'=>'ギュー',
        ],
         [
          'id'=>'19',
          'technique_id'=>'6',
          'name'=>'キュー',
        ],
        [
          'id'=>'20',
          'technique_id'=>'6',
          'name'=>'ズキューン',
        ],
        [
          'id'=>'21',
          'technique_id'=>'7',
          'name'=>'ズンズン',
        ],
         [
          'id'=>'22',
          'technique_id'=>'7',
          'name'=>'ザクザク',
        ],
        [
         'id'=>'23',
         'technique_id'=>'8',
         'name'=>'チャカチャカ',
        ],
        [
         'id'=>'24',
         'technique_id'=>'8',
         'name'=>'チャキチャキ',
        ],
         [
         'id'=>'25',
         'technique_id'=>'8',
         'name'=>'チキチキ',
        ],
        [
          'id'=>'26',
          'technique_id'=>'9',
          'name'=>'ミョーン',
        ],
         [
          'id'=>'27',
          'technique_id'=>'9',
          'name'=>'ミャーン',
        ],
         [
          'id'=>'28',
          'technique_id'=>'9',
          'name'=>'チョーン',
        ],
        [
          'id'=>'29',
          'technique_id'=>'10',
          'name'=>'ニュン',
        ],
         [
          'id'=>'30',
          'technique_id'=>'10',
          'name'=>'ニュンニュン',
        ],
        [
          'id'=>'31',
          'technique_id'=>'10',
          'name'=>'チューン',
        ],
        [
         'id'=>'32',
         'technique_id'=>'11',
         'name'=>'リルリル',
        ],
        [
         'id'=>'33',
         'technique_id'=>'11',
         'name'=>'ピロピロ',
        ],
         [
         'id'=>'34',
         'technique_id'=>'11',
         'name'=>'トゥルトゥル',
        ],
        [
         'id'=>'35',
         'technique_id'=>'12',
         'name'=>'ピロロ',
        ],
         [
         'id'=>'36',
         'technique_id'=>'12',
         'name'=>'ピロロピロロ',
        ],
         [
         'id'=>'37',
         'technique_id'=>'12',
         'name'=>'トゥルル',
        ],
         [
         'id'=>'38',
         'technique_id'=>'12',
         'name'=>'トゥルルトゥルル',
        ],
        [
         'id'=>'39',
         'technique_id'=>'13',
         'name'=>'ドゥーン',
        ],
         [
         'id'=>'40',
         'technique_id'=>'13',
         'name'=>'ドゥオーン',
        ],
         [
         'id'=>'41',
         'technique_id'=>'13',
         'name'=>'ドゥウィーン',
        ],
        ]
      );
    }
}
